spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/su?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    password: root
    username: root
    max-active: 10
    min-idle: 5
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
      enabled: true
      file-size-threshold: 0